version: '3'

services:
  #mdbook:
  #  image: hillliu/mdbook
  #  command: ["serve", "-d","/zlg", "-p", "5000", "-n", "0.0.0.0"]
  #  environment:
  #    - MDBOOK_BOOK__SITEURL="zlg"
  #  networks:
  #    - docs-net
  #  volumes:
  #    - "${SRC:-./zlg_docs/mdbook-demo}:/mdbook" 
  #    - "${DEST:-./zlg_docs/build/book}:/mdbook/book" 
  #  expose:
  #    - "5000"
  #    - "5001"

  docs:
    image: awesometic/docusaurus:latest
    command: ["serve", "--host", "0.0.0.0"]
    environment:
      - AUTO_UPDATE=false
      - WEBSITE_NAME=zlg_docs
      - TEMPLATE=classic
      - TARGET_UID=1000
      - TARGET_GID=1000
    volumes:
      - ./docs:/docusaurus
    networks:
      - docs-net
    expose:
      - "80"
    restart: always

  portal-keycloak: 
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_ADDR=postgres:5432
      - DB_DATABASE=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/keycloak-dump.json
      - JAVA_OPTS=-server -Xms1024m -Xmx1024m 
      - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy 
    volumes:
      - ./portal_docker/keycloak/keycloak-dump.json:/tmp/keycloak-dump.json
    networks:
      - ehrbase-net
      - num-net
    expose:
      - "8080"
      - "8443"
    restart: on-failure

  num-webapp:
    #image: docker.gitlab.gwdg.de/medinf/kvf/kardio/dzhk/cofoni/num-portal-webapp:1.8.0-dev-808cf071
    image: numresearchdataplatform/num-portal-webapp:1.9.0
    networks:
      - num-net
    volumes:
      - ./portal_docker/config.deploy.json:/usr/share/nginx/html/assets/config/config.deploy.json
    expose:
      - "80"
    restart: always
     
  num-portal:
    #image: docker.gitlab.gwdg.de/medinf/kvf/kardio/dzhk/cofoni/num-portal:1.8.0-dev-d63c2f21
    image: numresearchdataplatform/num-portal:1.9.0
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DATABASE_SERVER=postgres:5432 #postgres:5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_ENDPOINT=http://portal-keycloak:8080 #Schicken von Daten an Backend (KC Auth)
      - KEYCLOAK_REALM=crr
      - KEYCLOAK_CLIENT_ID=num-portal
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_CANONICAL_URL=https://portal-keycloak:8443 #Abruf Daten vom Portal (KC Auth)
      - EHRBASE_ENDPOINT=http://portal-ehrbase:8080
      - EHRBASE_USER=${SECURITY_AUTHADMINUSER}
      - EHRBASE_PASSWORD=${SECURITY_AUTHADMINPASSWORD}
      - ATNA_ENABLED=false
      - ATNA_HOST=localhost
      - ATNA_PORT=1234
      - ZARS_ENABLED=false
      - ZARS_EMAIL=mail
      - EMAIL_PORT=25
      - EMAIL_HOST=localhost
      - MANAGEMENT_PORT=8091
      - SWAGGER_OAUTH2_CLIENT-NAME=num-portal-webapp
      - PRIVACY_MIN_HITS=5
      - PSEUDONYMITY_SECRET=${PSEUDONYMITY_SECRET}
    expose:
      - "8090"
    networks:
      - ehrbase-net
      - num-net
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      #- ./.pgdata:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ehrbase-net
      - num-net
    expose:
      - "5432"
    #ports:     #useful for setup
    #  - 5432:5432
    restart: always

  portal-ehrbase:
    image: ehrbase/ehrbase:latest #0.18.3 #latest
    expose:
      - "8080"
    networks:
      - ehrbase-net
      - num-net
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/ehrbase
      - DB_USER=${EB_DB_USER}
      - DB_PASS=${EB_DB_PASS}
      - SERVER_NODENAME=local.ehrbase.org
      - SECURITY_AUTHTYPE=BASIC
      - SECURITY_AUTHUSER=${SECURITY_AUTHUSER}
      - SECURITY_AUTHPASSWORD=${SECURITY_AUTHPASSWORD}
      - SECURITY_AUTHADMINUSER=${SECURITY_AUTHADMINUSER}
      - SECURITY_AUTHADMINPASSWORD=${SECURITY_AUTHADMINPASSWORD}
      - SYSTEM_ALLOW_TEMPLATE_OVERWRITE=true
      - ADMIN_API_ACTIVE=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE=env,health,info,metrics,prometheus
      - MANAGEMENT_ENDPOINTS_WEB_BASEPATH=/management
      - MANAGEMENT_ENDPOINT_ENV_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_DATASOURCE_ENABLED=false
      - MANAGEMENT_ENDPOINT_INFO_ENABLED=false
      - MANAGEMENT_ENDPOINT_METRICS_ENABLED=false
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=false
      #- SERVER_DISABLESTRICTVALIDATION=false
      #- AQLCONFIGUSEJSQUERY=false
    depends_on:
      - postgres
    restart: on-failure

  portal-adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
        - ehrbase-net
        - num-net
    expose:
      - "8080"
    ports:  #Open Port to access DB from outside - only for setup
      - 5050:8080

  # portal-pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.de
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   networks:
  #       - ehrbase-net
  #   ports:
  #       - 5050:80

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - ehrbase-net
      - num-net
      - docs-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - nginx_html:/etc/nginx/html  # hinzugefuegt
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email jendrik.richter@med.uni-goettingen.de -d c100-099.cloud.gwdg.de --agree-tos #--test-cert for testing with massively increased rate limits

volumes:
  nginx_html:
  postgres_data:
  docusaurus_src:

networks:
  ehrbase-net: {}
  docs-net: {}
  num-net: {}