version: '3'

services:
  ehrbase:
    image: ehrbaseorg/ehrbase:next #use ehrbase/ in the future
    ports:
      - 80:8080
    networks:
      - ehrbase-net
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      SECURITY_AUTHTYPE: BASIC
      AUTH_USER: ehrbase-user
      AUTH_PASSWORD: SuperSecretPassword
      SYSTEM_NAME: local.ehrbase.org
    restart: always

  ehrdb:
    image: ehrbaseorg/ehrbase-postgres:latest
    ports: #may not need to be exposed in prod since docker bridges do the trick
      - 5432:5432
    networks:
      - ehrbase-net
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase

networks:
  ehrbase-net: {}

#volumes:
  #pgdata:
