version: '3'

services:
  ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 80:8080
    networks:
      - ehrbase-net
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: postgres
      DB_PASS: postgres
      SECURITY_AUTHTYPE: BASIC
      AUTH_USER: ehrbase-user
      AUTH_PASSWORD: SuperSecretPassword
      SYSTEM_NAME: local.ehrbase.org
    restart: always

  ehrdb:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5432:5432
    networks:
      - ehrbase-net
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase

networks:
  ehrbase-net: {}
