version: '3'

services:
  ehrbase:
    image: ehrbase/ehrbase:latest
    expose:
      - "8080"
    networks:
      - ehrbase-net
    env_file:
      - ./ehrbase_docker/.env.ehrbase
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
    restart: always

  mdbook:
    image: hillliu/mdbook
    command: ["serve", "-p", "5000", "-n", "0.0.0.0"]
    networks:
      - docs-net
    volumes:
      - "${SRC:-./zlg_docs/mdbook-demo}:/mdbook" 
      - "${DEST:-./zlg_docs/build/book}:/mdbook/book" 
    expose:
      - "5000"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - ehrbase-net
      - docs-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email jendrik.richter@med.uni-goettingen.de -d c100-099.cloud.gwdg.de --agree-tos

  ehrdb:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5432:5432
    networks:
      - ehrbase-net
    volumes:
      - ./ehrbase_docker/.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
    restart: always

networks:
  ehrbase-net: {}
  docs-net: {}
