version: '3'

volumes:
  postgres_data:
      driver: local

services:
  portal-keycloak: 
      image: jboss/keycloak:latest
      environment:
        - KEYCLOAK_USER=admin
        - DB_VENDOR=h2
        - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      networks:
        - ehrbase-net
      ports:
        #- 8180:8080
        - 8443:8443
      restart: on-failure

  postgres:
      image: postgres
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
        - ./.pgdata:/var/lib/postgresql/data
      networks:
        - ehrbase-net
        - db-net
      ports:
        - 5432:5432

  num-webapp:
      image: docker.gitlab.gwdg.de/medinf/kvf/kardio/dzhk/cofoni/num-portal-webapp:1.8.0-dev-808cf071
      volumes:
        - ./config.deploy.json:/usr/share/nginx/html/assets/config/config.deploy.json
      ports:
        - 80:80
     
  num-portal:
    image: docker.gitlab.gwdg.de/medinf/kvf/kardio/dzhk/cofoni/num-portal:1.8.0-dev-d63c2f21
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DATABASE_SERVER=postgres:5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - KEYCLOAK_ENDPOINT=http://portal-keycloak:8080
      - KEYCLOAK_REALM=crr
      - KEYCLOAK_CLIENT_ID:=num-portal
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_CANONICAL_URL=http://141.5.100.99:8080 #8443
      - EHRBASE_ENDPOINT=http://portal-ehrbase:8080
      - EHRBASE_USER=${SECURITY_AUTHADMINUSER}
      - EHRBASE_PASSWORD=${SECURITY_AUTHADMINPASSWORD}
      - ATNA_ENABLED='false'
      - ATNA_HOST=localhost
      - ATNA_PORT=1234
      - ZARS_ENABLED='false'
      - ZARS_EMAIL=mail
      - EMAIL_PORT=25
      - EMAIL_HOST=localhost
      - MANAGEMENT_PORT=8091
      - SWAGGER_OAUTH2_CLIENT-NAME=num-portal-webapp
      - PRIVACY_MIN_HITS=5
      - PSEUDONYMITY_SECRET=${PSEUDONYMITY_SECRET}
    ports:
      - 8090:8090
    networks:
      - ehrbase-net
    depends_on:
      - postgres

  portal-adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
        - db-net
    ports:
        - 5050:8080

  portal-ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 8080:8080
    networks:
      - ehrbase-net
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/ehrbase
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SERVER_NODENAME=local.ehrbase.org
      - SECURITY_AUTHTYPE=BASIC
      - SECURITY_AUTHUSER=${SECURITY_AUTHUSER}
      - SECURITY_AUTHPASSWORD=${SECURITY_AUTHPASSWORD}
      - SECURITY_AUTHADMINUSER=${SECURITY_AUTHADMINUSER}
      - SECURITY_AUTHADMINPASSWORD=${SECURITY_AUTHADMINPASSWORD}
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE=env,health,info,metrics,prometheus
      - MANAGEMENT_ENDPOINTS_WEB_BASEPATH=/management
      - MANAGEMENT_ENDPOINT_ENV_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_DATASOURCE_ENABLED=false
      - MANAGEMENT_ENDPOINT_INFO_ENABLED=false
      - MANAGEMENT_ENDPOINT_METRICS_ENABLED=false
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=false
    depends_on:
      - postgres
    restart: on-failure

networks:
  ehrbase-net: {}
  db-net: {}
