version: '3'

services:
  ehrbase:
    # I worked with 0.16.5 before. Testing 0.17.2 to post Issue at EHRBase GIT -> 17.2 braucht volle COmposer info. Mal testen..
    image: ehrbase/ehrbase:latest
    ports:
      - 80:8080
    networks:
      - ehrbase-net
    env_file:
      - .env.ehrbase
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
    restart: always

  ehrdb:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5432:5432
    networks:
      - ehrbase-net
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
    restart: always

networks:
  ehrbase-net: {}
