[book]
authors = ["Jendrik Richter"]
language = "en"
src = "src"
title = "ZL-Gesundheit-Docs.io - Utilization of openEHR for research data"
description = "Docs regarding installation, configuration and usage of the \"ZLG\" platform, tools and scripts for Research Data Management in collaborative Research Projects."

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.plantuml]
plantuml-cmd="java -jar /app/plantuml.jar"

[output.html]
mathjax-support = true
site-url = "/zlg/"
additional-css = ["assets/mermaid.css", "assets/print.css"]
additional-js = ["assets/mermaid.min.js", "assets/import-html.js"]

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
